// Generates typst/templates.gen.ts from the .typ sources.
//
// Why this exists: Supabase's bundler ships only files reachable through the module
// graph, so Deno.readTextFile("./typst/common.typ") fails at runtime with "path not
// found", and `import ... with { type: "text" }` is rejected outright ("The import
// attribute type of \"text\" is unsupported"). Embedding the sources in a .ts module is
// the one form the bundler carries.
//
// The .typ files stay the source of truth — edit those, keep tinymist/LSP working.
// preview.ts runs this on every run, so the generated file cannot drift in normal use.
// Run standalone before deploying: deno run -A build-templates.ts

const here = new URL(".", import.meta.url).pathname;
const NAMES = ["common.typ", "report.typ"];

export async function buildTemplates(): Promise<string> {
  const entries: [string, string][] = [];
  for (const n of NAMES) {
    entries.push([n, await Deno.readTextFile(`${here}typst/${n}`)]);
  }
  const body = entries
    .map(([n, src]) => `  ${JSON.stringify(n)}: ${JSON.stringify(src)},`)
    .join("\n");
  return `// GENERATED by build-templates.ts — do not edit. Edit typst/*.typ instead.\n` +
    `export const TEMPLATES: Record<string, string> = {\n${body}\n};\n`;
}

if (import.meta.main) {
  const out = `${here}typst/templates.gen.ts`;
  await Deno.writeTextFile(out, await buildTemplates());
  console.log(`wrote ${out}`);
}
