// State handling for the ORCID broker, kept separate from index.ts so it can
// be tested without a network, a database or a deployed function. This is the
// part of the broker that decides where a browser may be redirected and which
// browser a callback belongs to, so it is the part most worth testing.

/// Return URLs the broker may redirect a browser to. A hard allowlist: without
/// it, `state` is an open redirector carrying a session token.
///
/// `localhost` is included only when the broker itself is running locally.
/// On the deployed function it is not: the success redirect carries a
/// magic-link token, so an attacker who can choose `state` could otherwise
/// steer a sign-in at whatever is listening on the victim's own machine.
export function allowedReturn(supabaseUrl: string): RegExp[] {
  const local = /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?(\/|$)/.test(
    supabaseUrl,
  );
  return [
    /^https:\/\/berlogabob\.github\.io\/Unidcom-IADE\/$/,
    ...(local
      ? [
        /^http:\/\/localhost(:\d+)?\/$/,
        /^http:\/\/127\.0\.0\.1(:\d+)?\/$/,
      ]
      : []),
  ];
}

export function isAllowedReturn(returnTo: string, supabaseUrl: string): boolean {
  return allowedReturn(supabaseUrl).some((re) => re.test(returnTo));
}

export type SignInState = { nonce: string; returnTo: string };

/// Sign-in state is `signin|<nonce>|<returnTo>`.
///
/// The nonce is generated by the app and kept in that browser's sessionStorage.
/// The broker does not validate it — it cannot, it holds no session — it simply
/// echoes it back on the success redirect. The *app* then refuses a callback
/// whose nonce does not match the one it generated.
///
/// That is what closes login-CSRF: previously `state` was a bare return URL, so
/// an attacker could complete their own ORCID authorization, capture the `code`,
/// and hand a victim a link that silently signed the victim's browser in **as
/// the attacker** — after which everything the victim typed went into the
/// attacker's account. A nonce the attacker cannot predict breaks that, because
/// the victim's browser only accepts a callback it started.
///
/// A bare URL is still parsed, as the legacy form, so a browser running a
/// cached build of the app is not locked out mid-deploy. Those clients do not
/// check the nonce and remain exposed until their cache turns over; the check
/// that matters lives in the app, not here.
export function parseSignInState(state: string): SignInState | null {
  if (!state) return null;
  if (!state.startsWith("signin|")) return { nonce: "", returnTo: state };
  const parts = state.split("|");
  if (parts.length !== 3) return null;
  const [, nonce, returnTo] = parts;
  if (!nonce || !returnTo) return null;
  return { nonce, returnTo };
}

export function buildSignInState(nonce: string, returnTo: string): string {
  return `signin|${nonce}|${returnTo}`;
}

/// Append the nonce to a redirect so the app can match it. Kept here rather
/// than inline so the escaping is covered by a test.
export function withNonce(url: string, nonce: string): string {
  if (!nonce) return url;
  const sep = url.includes("?") ? "&" : "?";
  return `${url}${sep}orcid_nonce=${encodeURIComponent(nonce)}`;
}

export type LinkState = { userId: string; returnTo: string };

/// Link state is `link|<userId>|<exp>|<returnTo>|<sig>`, HMAC-signed because
/// unlike sign-in it asserts *which account* is linking.
///
/// `sign` is injected so tests can exercise expiry and tampering without the
/// service-role key.
export async function parseLinkState(
  state: string,
  sign: (data: string) => Promise<string>,
  now: () => number = () => Date.now() / 1000,
): Promise<LinkState | null> {
  const parts = state.split("|");
  if (parts.length !== 5 || parts[0] !== "link") return null;
  const [, userId, exp, returnTo, sig] = parts;
  const expected = await sign(`link|${userId}|${exp}|${returnTo}`);
  if (!timingSafeEqual(expected, sig)) return null;
  if (!Number.isFinite(Number(exp)) || Number(exp) < now()) return null;
  return { userId, returnTo };
}

/// Constant-time string compare. `!==` short-circuits on the first differing
/// byte; this is an authorization decision, so it should not leak where the
/// mismatch was.
export function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}
