-- Output taxonomy (the director's classification behind outputs.category_path),
-- seeded from "Lista de producoes UNIDCOM 2025.xlsx". Ragged tree, 1-4 levels deep;
-- each row is a leaf path, intermediate nodes are derived from shared prefixes.
create table public.output_taxonomy (
  id uuid primary key default gen_random_uuid(),
  segments text[] not null unique,
  sort_order int not null
);
alter table public.output_taxonomy enable row level security;
create policy ot_read  on public.output_taxonomy for select using (true);
create policy ot_write on public.output_taxonomy for all using (public.is_admin()) with check (public.is_admin());

insert into public.output_taxonomy (segments, sort_order) values
  (array['Livros','Autoria de Livro','Publicação de livro científico com indexação ISI ou Scopus ou equivalentes','Único autor'], 0),
  (array['Livros','Autoria de Livro','Publicação de livro científico com indexação ISI ou Scopus ou equivalentes','Co-autor'], 1),
  (array['Livros','Autoria de Livro','Publicação de livro científico não indexado','Único autor'], 2),
  (array['Livros','Autoria de Livro','Publicação de livro científico não indexado','Co-autor'], 3),
  (array['Livros','Edição de livro','Edição e coordenação de livro científico com indexação ISI ou Scopus ou equivalentes','Único editor'], 4),
  (array['Livros','Edição de livro','Edição e coordenação de livro científico com indexação ISI ou Scopus ou equivalentes','Co-editor'], 5),
  (array['Livros','Edição de livro','Edição e coordenação de livro científico não indexado','Único editor'], 6),
  (array['Livros','Edição de livro','Edição e coordenação de livro científico não indexado','Co-editor'], 7),
  (array['Livros','Capítulos de livros','Capítulos de livros indexados ISI e Scopus ou equivalentes','Único autor'], 8),
  (array['Livros','Capítulos de livros','Capítulos de livros indexados ISI e Scopus ou equivalentes','Primeiro autor'], 9),
  (array['Livros','Capítulos de livros','Capítulos de livros indexados ISI e Scopus ou equivalentes','Co-autor'], 10),
  (array['Livros','Capítulos de livros','Atas de congressos com indexação ISI e Scopus ou equivalentes','Único autor'], 11),
  (array['Livros','Capítulos de livros','Atas de congressos com indexação ISI e Scopus ou equivalentes','Primeiro autor'], 12),
  (array['Livros','Capítulos de livros','Atas de congressos com indexação ISI e Scopus ou equivalentes','Co-autor'], 13),
  (array['Livros','Capítulos de livros','Capítulos de livros não indexados','Único autor'], 14),
  (array['Livros','Capítulos de livros','Capítulos de livros não indexados','Primeiro autor'], 15),
  (array['Livros','Capítulos de livros','Capítulos de livros não indexados','Co-autor'], 16),
  (array['Livros','Capítulos de livros','Atas de congressos não indexados','Único autor'], 17),
  (array['Livros','Capítulos de livros','Atas de congressos não indexados','Primeiro autor'], 18),
  (array['Livros','Capítulos de livros','Atas de congressos não indexados','Co-autor'], 19),
  (array['Artigos em revistas','Artigo em revista científica de quartil Q1','Único autor'], 20),
  (array['Artigos em revistas','Artigo em revista científica de quartil Q1','Primeiro autor'], 21),
  (array['Artigos em revistas','Artigo em revista científica de quartil Q1','Co-autor'], 22),
  (array['Artigos em revistas','Artigo em revista científica de quartil Q2','Único autor'], 23),
  (array['Artigos em revistas','Artigo em revista científica de quartil Q2','Primeiro autor'], 24),
  (array['Artigos em revistas','Artigo em revista científica de quartil Q2','Co-autor'], 25),
  (array['Artigos em revistas','Artigo em revista científica de quartil Q3','Único autor'], 26),
  (array['Artigos em revistas','Artigo em revista científica de quartil Q3','Primeiro autor'], 27),
  (array['Artigos em revistas','Artigo em revista científica de quartil Q3','Co-autor'], 28),
  (array['Artigos em revistas','Artigo em revista científica de quartil Q4','Único autor'], 29),
  (array['Artigos em revistas','Artigo em revista científica de quartil Q4','Primeiro autor'], 30),
  (array['Artigos em revistas','Artigo em revista científica de quartil Q4','Co-autor'], 31),
  (array['Artigos em revistas','Artigo em revista científica não indexada','Único autor'], 32),
  (array['Artigos em revistas','Artigo em revista científica não indexada','Primeiro autor'], 33),
  (array['Artigos em revistas','Artigo em revista científica não indexada','Co-autor'], 34),
  (array['Conferência em congressos (sem publicação)'], 35),
  (array['Organização de Seminários e Conferências','Chair de conferências indexadas'], 36),
  (array['Organização de Seminários e Conferências','Chair de conferências não indexadas'], 37),
  (array['Organização de Seminários e Conferências','Membro da comissão organizadora de conferência indexada'], 38),
  (array['Organização de Seminários e Conferências','Membro de comissão organizadora de conferência não indexada'], 39),
  (array['Organização de Seminários e Conferências','Membro da comissão científica de conferência indexada'], 40),
  (array['Organização de Seminários e Conferências','Membro de comissão científica de conferência não indexada'], 41),
  (array['Formação avançada','Orientação de doutoramento concluída'], 42),
  (array['Formação avançada','Orientação de mestrado concluída'], 43),
  (array['Formação avançada','Orientação de pós-doutoramento concluída'], 44),
  (array['Formação avançada','Participação em júri de mestrado'], 45),
  (array['Formação avançada','Participação em júri de doutoramento'], 46),
  (array['Formação avançada','Formação adquirida'], 47),
  (array['Participação em projectos de investigação','Projeto de investigação internacional financiado','Coordenação'], 48),
  (array['Participação em projectos de investigação','Projeto de investigação internacional financiado','Membro'], 49),
  (array['Participação em projectos de investigação','Projeto de investigação nacional financiado','Coordenação'], 50),
  (array['Participação em projectos de investigação','Projeto de investigação nacional financiado','Membro'], 51),
  (array['Participação em projectos de investigação','Projeto de investigação internacional (não financiado)','Coordenação'], 52),
  (array['Participação em projectos de investigação','Projeto de investigação internacional (não financiado)','Membro'], 53),
  (array['Participação em projectos de investigação','Projeto de investigação nacional (não financiado)','Coordenação'], 54),
  (array['Participação em projectos de investigação','Projeto de investigação nacional (não financiado)','Membro'], 55),
  (array['Reconhecimento pela comunidade científica','Prémios e distinções em sociedade científica internacional'], 56),
  (array['Reconhecimento pela comunidade científica','Prémios e distinções em sociedade científica nacional'], 57),
  (array['Reconhecimento pela comunidade científica','Orador por convite em conferências indexadas'], 58),
  (array['Reconhecimento pela comunidade científica','Orador por convite em conferências não indexadas'], 59),
  (array['Missões de internacionalização no âmbito de projetos científicos'], 60),
  (array['Valorizações de atividades ou outros outputs no âmbito de projetos científicos','Exposições'], 61),
  (array['Valorizações de atividades ou outros outputs no âmbito de projetos científicos','Catálogos'], 62),
  (array['Valorizações de atividades ou outros outputs no âmbito de projetos científicos','Workshops e similares'], 63),
  (array['Valorizações de atividades ou outros outputs no âmbito de projetos científicos','Outros'], 64),
  (array['Patentes e contratos industriais','Patentes'], 65),
  (array['Patentes e contratos industriais','Contratos industriais'], 66),
  (array['Actividades de gestão e auxílio à UNIDCOM','Participação em comissões de trabalho internas e externas'], 67),
  (array['Actividades de gestão e auxílio à UNIDCOM','Participação de actividade de apoio à investigação interna e externa'], 68),
  (array['Actividades de gestão e auxílio à UNIDCOM','Participação em momentos de transferência de conhecimento para a sociedade civil'], 69),
  (array['Actividades de gestão e auxílio à UNIDCOM','Apoio nas conferências'], 70),
  (array['Actividades de gestão e auxílio à UNIDCOM','Realização de outros eventos científicos'], 71),
  (array['Actividades de gestão e auxílio à UNIDCOM','Actividades de promoção'], 72),
  (array['Actividades de gestão e auxílio à UNIDCOM','Outras'], 73);
